services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5056:5056'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - HOST=${HOST}
      - MODE=${MODE}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CODE_SEED=${CODE_SEED}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE}
      - EMAIL_FROM=${EMAIL_FROM}

    networks:
      - app_network

networks:
  app_network:
    driver: bridge
